ssh-keyscan hadoop >>  ~/.ssh/known_hosts
ssh-keyscan spark1 >>  ~/.ssh/known_hosts
ssh-keyscan spark2 >>  ~/.ssh/known_hosts
ssh-keyscan spark3 >>  ~/.ssh/known_hosts
ssh-keyscan spark4 >>  ~/.ssh/known_hosts
ssh-keyscan spark5 >>  ~/.ssh/known_hosts
ssh-keyscan spark6 >>  ~/.ssh/known_hosts
ssh-keyscan spark7 >>  ~/.ssh/known_hosts
ssh-keyscan spark8 >>  ~/.ssh/known_hosts
ssh-keyscan spark9 >>  ~/.ssh/known_hosts
ssh-keyscan spark10 >>  ~/.ssh/known_hosts
ssh-keyscan spark11 >>  ~/.ssh/known_hosts
ssh-keyscan spark12 >>  ~/.ssh/known_hosts
ssh-keyscan spark13 >>  ~/.ssh/known_hosts
ssh-keyscan spark14 >>  ~/.ssh/known_hosts
ssh-keyscan spark15 >>  ~/.ssh/known_hosts
